version: '3'

services:

  db:
    image: postgres:15-alpine
    ports:
      - "5432:5432" 
    environment:
      - POSTGRES_DB=cartelera
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=picateclasUnahur
    volumes:
      - ./docker/postgres/data:/var/lib/postgresql/data
      - ./docker/postgres/init:/docker-entrypoint-initdb.d/

  app:
    image: valentinochiappanni07/backend:v6.0.10
    ports:
      - "4000:4000"
      - "1234:1234"
    environment:
      - DATABASE_HOST=db  #Host de la base de datos.
      - DATABASE_PORT=5432  #Puerto de la base de datos.
      - DATABASE_NAME=cartelera #Nombre de la base de datos.
      - DATABASE_USER=postgres #Usuario de la base de datos.
      - DATABASE_PASSWORD=picateclasUnahur #Contraseña de la base de datos.
      - HOST=http://186.12.145.198 #Host de la api.
      - PORT=4000 #Puerto de la api.
    volumes:
      - ./assets:/usr/src/app/dist/assets #Ruta para persistir archivos. (Cambiar solo lado derecho).

  front:
    image: valentinochiappanni07/frontend:v6.0.11
    ports:
      - "80:80"
