version: '3'

services:

  db:
    image: postgres:latest
    ports:
      - "5432:5432" 
    environment:
      - POSTGRES_DB=cartelera
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=picateclasUnahur
    volumes:
      - ./docker/postgres/data:/var/lib/postgresql/data
      - ./docker/postgres/init:/docker-entrypoint-initdb.d/

  app:
    image: valentinochiappanni07/backend:v3.0.0
    ports:
      - "4000:4000"
      - "1234:1234"
    environment:
      - DATABASE_HOST=db
      - DATABASE_PORT=5432  
      - DATABASE_NAME=cartelera
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=picateclasUnahur
    volumes:
      - ./public:/usr/src/app/public

  front:
    image: valentinochiappanni07/frontend:v3.0.0
    ports:
      - "80:80"